#!/bin/bash

if [[ "$1" == "" ]]
then 
 echo "Usage: ./js-build-src-clean TMPID"
 exit
fi

mkdir -p builds 
mkdir -p serve

# just in case 
rm -fR builds/$1
rm -fR serve/$1
 
cp -a js-base builds/$1

cp /tmp/$1 builds/$1/src/App.js

cd builds/$1 
npm run build
cd ../..
mv builds/$1/build serve/$1

#cleanup
rm -fR builds/$1 
rm -f /tmp/$1
