#!/bin/bash

if [[ "$1" == "" ]]
then 
 echo "Usage: ./ts-build-src TMPID"
 exit
fi

mkdir -p builds 
mkdir -p serve

# just in case 
rm -fR builds/$1
rm -fR serve/$1
 
cp -a ts-base builds/$1

cp /tmp/$1 builds/$1/src/App.tsx

cd builds/$1 
npm run build
cd ../..
mv builds/$1/build serve/$1

#cleanup
# rm -fR builds/$1 
# rm -f /tmp/$1

